### ISSUE TITLE
مشکل در تغییر تصویر هنگام ارسال وب پوش

### ISSUE THREAD

**Issue by webtinax** [chabokpush/chabok-client-js#1]
سلام و وقت بخیر خدمت تیم شما

ممنون بابت سامانه فوق العاده کارآمد و عالی که دارید ،  من با پی اچ پی میخوام وب پوش بزنم هنگام ارسال تصویر پیشفرض چابک آورده میشه و عنوان را هم نتونستیم تغییر بدیم ، لطفا در این خصوص راهنمایی بفرمائید

مورد دیگر اینکه در خصوص این پارامترها و کاربرد اونها چطور میتونیم اطلاعات دقیق بدست بیاریم ؟

```json
{
  "user": "string",
  "channel": "string",
  "content": "string",
  "data": {},
  "trackId": "string",
  "inApp": false,
  "live": false,
  "useAsAlert": false,
  "alertText": "string",
  "ttl": 0,
  "fallback": {},
  "clientId": "string",
  "notification": {
    "title": "string",
    "body": "string",
    "sound": "string",
    "actions": [
      {}
    ],
    "mediaType": "string",
    "mediaUrl": "string",
    "contentAvailable": true,
    "mutableContent": true,
    "category": "string"
  },
  "idr": false,
  "silent": true,
  "contentBinary": "string",
  "contentType": "string",
  "id": 0
}
```

**Comment by amir-yaghoobi** [comment]
سلام

> من با پی اچ پی میخوام وب پوش بزنم هنگام ارسال تصویر پیشفرض چابک آورده میشه

به منظور نمایش آیکون شما باید در کلید `data` مقدار `icon` را قرار دهید.
```
data: {
   icon: "http://path-to-icon.png"
}
```
> عنوان را هم نتونستیم تغییر بدیم 
این مشکل از سمت sdk ما بود و در نسخه 0.4.4 رفع شده است.

> مورد دیگر اینکه در خصوص این پارامترها و کاربرد اونها چطور میتونیم اطلاعات دقیق بدست بیاریم ؟

در قسمت [مستندات](https://api.doc.chabokpush.com/#/) و تغییر تب از `Example value` به `Model` میتوانید اطلاعات دقیق تری نسبت به هر پارامتر بدست بیاورید

**Comment by amir-yaghoobi** [comment]
<div dir="rtl">
من این issue رو می‌بندم اگر همچنان مشکل داشتن دوباره باز کنین.

</div>
