### ISSUE TITLE
حذف تمامی تگ های کاربر

### ISSUE THREAD

**Issue by webtinax** [chabokpush/chabok-client-js#10]
لطفا امکانی افزوده شود تا بشه کل تگ های ثبت شده را بدون اشاره به نام تگ ها حذف کنیم

**Comment by webtinax** [comment]
لطفا اگر ممکنه نسخه جدید زودتر منتشر بشه سیستم ما لنگ این مورده ممنون

**Comment by behrad** [comment]
در حال حاضر از چه نسخه ای استفاده می کنید؟

تا اواخر هفته دیگه یک نسخه پچ ریلیز می کنیم

**Comment by webtinax** [comment]
نسخه ۱.۰.۱ استفاده میکنم
