### ISSUE TITLE
مشکل دسترسی به حساب کاربری

### ISSUE THREAD

**Issue by webtinax** [chabokpush/chabok-client-js#11]
سلام وقت بخیر سایت باز نمیشه

https://sandbox.push.adpdigital.com/login

![sadasdfgsgsdgsd](https://user-images.githubusercontent.com/14169430/45692924-2a4a2180-bb71-11e8-8047-90357c0d8392.PNG)

با چند مرورگر و چند سیستم تست گرفتم این مشکل هست

**Comment by behrad** [comment]
پنل چابک حجم بارگذاری اولیه‌اش زیاد هست و ممکن هست در بعضی مواقع که پهنای باند اینترنت شما افت ممیکنه مشکلی در باز کردنش داشته باشید
لطفن مجددن تست بفرمایید و پهنای باند نت خود رو کنترل کنید

**Comment by webtinax** [comment]
Failed to load resource: net::ERR_CONNECTION_RESET
app-1f91da0379.js:1 Failed to load resource: net::ERR_CONNECTION_RESET
vendor-abee127352.js:1 Failed to load resource: net::ERR_CONNECTION_RESET

متاسفانه صدها بار تست کردم با چند سیستم چند اینترنت شامل ای دی اس ال اینترنت گوشی و حتی توی مرورگرهای مختلف

**Comment by webtinax** [comment]
ممنون مشکل با فیلترشکن برطرف شد
