### ISSUE TITLE
تغییر و مشکل

### ISSUE THREAD

**Issue by webtinax** [chabokpush/chabok-client-js#12]
![dsfsdfsdf](https://user-images.githubusercontent.com/14169430/45697634-7732f580-bb7b-11e8-98d0-5b2148fa7f2c.PNG)

سلام و وقت بخیر خدمت شما
از 10 روز پیش ما نمودارهای آماری اعضای انلاینمون مشکل پیدا کرده من امروز نشستم بررسی کردن ، دیدم انگار شما توی سیستم تغییری دادید که کانکت مجدد انجام نمیشه در واقع یه حالی شده سیستم نمیدونم این بخاطر اپدیت هست و بهینه سازی شدن یا ... اما مهم اینه ما دیگه کاربرانمون رو نمیتونیم انلاین شدنشون را ببینیم من اتصال دارم و حتی شناسه کاربر رو هم میتونم دریافت کنم اما

مثلا کد زیر کار نمیکنه دیگه ::
`chabok.on('connected',function () {
                console.log('is connected to push server');
            });`

**Comment by webtinax** [comment]
فقط کاربرانی که برای اولین بار وارد سیستم میشند کانکت براشون اجرا میشه ، یعنی کاربر یکبار کانکت میشه و دیگه انگار کانکت باقی میمونه

**Comment by behrad** [comment]
از لاگ کنسول می تونید خطایی اگه میده برامون بفرستید
اگر اطلاعات حساسی توش هست لاگ رو می تونید ایمیل کنید

**Comment by webtinax** [comment]
ببینید من گفتم هربار که چابک کانکت شد در کنسول پیامی بیاد که کانکت انجام شده

قبلا هر صفحه از سایت باز میشد یکبار پیام می امد که کانکت انجام شد و داخل حساب کاربری هم میزد کاربر انلاین شده و امار و همه درست بود ، الان فقط موقع ثبت نام کاربر در چابک کانکت انجام میشه و با رفرش شدن صفحه کانکت فراخوانی نمیشه

ارور خاصی دریافت نمیشه بلکه انگار کانکت فراخوانی نمیشه

لطفا این مورد را بررسی نمایید مشکل از طرف سیستم شما بوجود اماده به این علت که ما بیش از 15 روز هست که کدها رو دست نزدیم اما مشکل گویا از 10 روز پیش بوجود اومده حالا من با سایت های دیگه ای که داریم هم این مورد را تست کرده و خبر میدم

**Comment by behrad** [comment]
اگر در تاریخ مذکور نسخه چابک خود رو به روز رسانی کرده اید مورد بالا رو بررسی کنید
و لطفن در هر آپدیت غیر از پچ ورژن از مطالعه [مستندات ارتقا نسخه چابک](https://doc.chabokpush.com/javascript/release-note.html#%D8%A7%D8%B1%D8%AA%D9%82%D8%A7-1) مطمئن بشید
