### ISSUE TITLE
بررسی وجود یک تگ

### ISSUE THREAD

**Issue by webtinax** [chabokpush/chabok-client-js#13]
سلام وقت بخیر 
چطور میشه بررسی کرد در هنگامی که کاربر در حال استفاده از سایت هست که آیا تگی را دارد یا خیر
به فرض مثال:

میخوام چک کنم ببینم کاربر تگ قیمت رو داره یا نه اگر داشت فلان دکمه روشن باشه و اگر نداشت اون دکمه خاموش بشه

این چک کردن توسط جاوا اسکریپت انجام میشه

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">این قابلیت در نسخه بعدی اضافه خواهد شد.</p>

**Comment by amir-yaghoobi** [comment]
سلام
تا هفته بعد احتمالا یک نسخه خواهیم داد

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">@webtinax </p>
<p dir="rtl"><a href="https://www.npmjs.com/package/chabokpush/v/1.0.2">نسخه ۱.۰.۲</a> منتشر شد</p>
<p dir="rtl">شما با استفاده از متد <code>getTags</code> می‌توانید لیست تگ‌های یک کاربر را دریافت نمایید.</p>
<p dir="rtl">نمونه:</p>

```javascript

chabok.getTags()
     .then(tags => {
          console.log(typeof tags) // array
          console.log('tags', tags) // ['sample_tag1', 'sample_tag2', .... ]
     })

```

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">من این issue رو می‌بندم، در صورتی که مشکلی در استفاده از این قابلیت داشتین دوباره باز کنین</p>
