### ISSUE TITLE
chabokpush.Chabok is not a constructor

### ISSUE THREAD

**Issue by rasez** [chabokpush/chabok-client-js#14]
سلام من پیاده سازی رو انجام دادم کدم هم به صورت زیر هست  من فقط میخوام یوزر رجیستر کنم توی جابک از طریق جاوااسکریپت ولی با این ارور مواجه میشم
`Uncaught TypeError: chabokpush.Chabok is not a constructor`
کد من هم به این صورت هست

```
<script src="https://unpkg.com/chabokpush@1.0.1/dist/chabokpush.min.js"></script>
<script src="<?= baseHtmlUrl() ?>/ChabokSDKWorker.js"></script>
<script>
var userId= "<?=UserHelper::getKey(SSN_TOKEN)?>"
const auth = {
  appId: 'APP_ID',
  apiKey: 'API_KEY',
  username: 'USERNAME',
  password: 'PASSWORD',
  devMode:true
}
const options = {
      webpush: {
        enabled: true,
        publicKey: 'PUBLIC_KEY'
      },
      silent: false,
    };
const chabok = new chabokpush.Chabok(auth, options)
chabok.on('registered', deviceId => console.log('DeviceId ', deviceId))

if (chabok.isRegistered()) {
    chabok.register(chabok.getUserId())
} else {
	chabok.register(userId)
	ajaxing("",{"token":userId},"/user/updateAdminToken");
}
</script>
```

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">این مشکل به خاطر وجود خط زیر در کد شما می‌باشد:</p>
<p><code>&lt;script src=&quot;&lt;?= baseHtmlUrl() ?&gt;/ChabokSDKWorker.js&quot;&gt;&lt;/script&gt;</code></p>
<p dir="rtl">همانطور که در این قسمت از <a href="https://doc.chabokpush.com/javascript/installation.html#%D8%A7%D9%81%D8%B2%D9%88%D8%AF%D9%86-service-worker">مستندات</a> گفته شده فایل <code>ChabokSDKWorker.js</code> لازم است در <code>root</code> پروژه شما قرار بگیرد و ایمپورت آن به این شکل اشتباه می‌باشد.</p>

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">مثلا اگه صفحه اصلی سایت شما فایل <code>index.html</code> باشد و شما آن را در پوشه <code>public</code> قرار داده‌اید، منظور از <code>root</code> در این جا یعنی داخل پوشه <code>public</code></p>

<blockquote dir="rtl">
<p dir="rtl">نکته: همانطور که قبلتر‌ هم اشاره کردم نیازی به ایمپورت فایل <strong>ChabokSDKWorker.js</strong> با استفاده از تگ 
<code>&lt;script&gt;</code> نمی‌باشد و در نتیجه خط <code><script src=&quot;&lt;?= baseHtmlUrl() ?&gt;/ChabokSDKWorker.js&quot;&gt;&lt;/script></code> را حذف نمایید.</p>
</blockquote>

**Comment by rasez** [comment]
من الان توکن میتونم ثبت کنم ولی پوش نوتیفیکیشن نمیگیرم فایل رو گذاشتم کنار فایل پی اچ پی که این کد داخلش هست

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">در صورتی که مشکل شما همچنان برطرف نشده، دوباره این issue رو باز کنین</p>

**Comment by AlirezaAzizi145** [comment]
من هم این مشکل رو دارم 
![1](https://user-images.githubusercontent.com/30459434/62933551-ad064b80-bdd7-11e9-9736-bafff7ede9e1.png)
![2](https://user-images.githubusercontent.com/30459434/62933552-ad9ee200-bdd7-11e9-9aa9-b18f54830f87.png)

**Comment by AlirezaAzizi145** [comment]
in moshkel be khatere tartib file hast `ChabokSDKWorker.js` bayad balatar az `chabokpush.min.js` bashe
