### ISSUE TITLE
مشکل در نمایش وب پوش

### ISSUE THREAD

**Issue by amir-yaghoobi** [chabokpush/chabok-client-js#16]
[#12](https://github.com/chabokpush/chabok-panel/issues/12)

**Comment by ehsan-dev** [comment]
سلام... بنده
 وب پوش را در حالت 
localhost و devmodel= true
تست کردم بدون مشکل کار میکرد... وقتی پابلیش کردم و در محیط اینترنت قرار گرفت در کنسول خطای 401 را می دهد
the server responded with a status of 401 (Unauthorized)
Error: Request failed with status code 401
مشکل از چیه؟
ممنون

**Comment by ehsan-dev** [comment]
درست شد..ممنون.... مشکل در وارد کردن آدرس سایت بود...
https://
را برداشتم درست شد... سپاس
