### ISSUE TITLE
ارسال پوش برای pwa

### ISSUE THREAD

**Issue by maebrahimi** [chabokpush/chabok-client-js#17]
<p dir="rtl">سلام</p>
<p dir="rtl">ما با ری‌اکت pwa توسعه دادیم و داخل مستندات ذکر کردید که &quot;نکته : اگر مرورگر شما بسته شده باشد، دریافت پوش‌نوتیفیکیشن امکان‌پذیر نیست.&quot;.</p>
<p dir="rtl">میخواستم بپرسم اگر یوزرها add to home screen کرده باشن پوش ارسال میشه یا نه؟</p>
<p dir="rtl">تشکر</p>

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">&quot;نکته : اگر مرورگر شما بسته شده باشد، دریافت پوش‌نوتیفیکیشن امکان‌پذیر نیست.&quot;.</p>
</blockquote>
<p dir="rtl">در سیستم عامل iOS امکان <a href="https://stackoverflow.com/questions/49745221/can-we-run-firebase-realtime-listening-on-ios-serviceworker/49803408#49803408">نمایش نوتیفیکیشن هنوز به سافاری</a> اضافه نشده است.</p>
<blockquote dir="rtl">
<p dir="rtl">میخواستم بپرسم اگر یوزرها add to home screen کرده باشن پوش ارسال میشه یا نه؟</p>
</blockquote>
<p dir="rtl">بر روی سیستم‌عامل اندروید کاربر پوش‌نوتیفیکیشن دریافت خواهد کرد اگر کاربر add to home screen کند زمانی که مرورگر بسته است نوتیفیکیشن نمایش داده می‌شود</p>
