### ISSUE TITLE
ثبت تگ بلافاصله بعد از رجیستر

### ISSUE THREAD

**Issue by mosi13** [chabokpush/chabok-client-js#18]
من بلافاصله بعد از رجیستر کردن اقدام به ثبت یا حذف یک تگ میکنم اما با خطای زیر مواجه میشم.
**_Error: user is not registered!_**

نمونه کدها :
`
chabok.register(ucID); 
`
`
chabok.addTag("Guest");
`

این متد رجیستر کال بک نداره که بعد از ثبت شدن بتونیم اقدام به ثبت تگ کنیم؟

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">سلام</p>
<p dir="rtl">متد <code>register</code> یک <code>Promise</code> بر میگردونه.</p>
<p dir="rtl">در نتیجه افزودن تگ را به بعد از <code>resolve</code> شدن این <code>Promise</code> منتقل کنید.</p>


```javascript
chabok.register(ucID)
           .then(device => {
                 chabok.addTag('Guest')
           })
```
