### ISSUE TITLE
ارور هنگام رجیسترکردن یوزر

### ISSUE THREAD

**Issue by shdehnavi** [chabokpush/chabok-client-js#20]
سلام 
میخوام از چابک پوش روی یک اپلیکیشن  `PWA`  استفاده کنم.
این اپلیکیشن با فریمورک `IONIC `نوشته شده و از `Angular5 `استفاده میشه.

بعد از نصب کتابخونه و ایمپورت کردن اون توی پروژه وقتی توی صفحه اصلیم مقداردهی های اولیه رو انجام میدم و خط زیر (که برای ثبت کاربر مهمان هست) رو اضافه می کنم ارور میگیرم.
`chabok.registerAsGuest();`
.

عکس مربوط به ارور دریافتی

![image](https://user-images.githubusercontent.com/6625055/52993834-d480ea80-342a-11e9-8b0c-3bf0fc2a16ce.png)

مشکل از کجا میتونه باشه؟ 
تشکر

**Comment by shdehnavi** [comment]
الان دوباره تست کردم، با اینکه این ارور رو میگیرم ولی توی پنل چابک میبینم که دستگاه ثبت شده، راه حلی برای رفع این ارور هست؟

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">سلام</p>
<p dir="rtl">خطای فوق زمانی رخ میدهد که سرویس ورکر نتواند توکن بگیرد</p>
<p dir="rtl">و از آنجایی که در iOS وب پوش توسط اپل پشتیبانی نمی‌شود امکان دریافت توکن نیست.</p>
<blockquote dir="rtl">
<p dir="rtl">با اینکه این ارور رو میگیرم ولی توی پنل چابک میبینم که دستگاه ثبت شده</p>
</blockquote>
<p dir="rtl">بله دستگاه ثبت می‌شود ولی توکنی برای ارسال به کاربر وجود نخواهد داشت</p>

**Comment by shdehnavi** [comment]
الان روی یک دستگاه اندروید در حال تست هستم، ارروری در کنسول دریافت نمیشود، وقتی از طریق پنل پیام ارسال می کنم در صف مانده و ارسال نمی شود، آیا باز هم مشکل عدم وجود توکن هست؟

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">آیا دستگاه از طریق vpn به اینترنت متصل هست؟</p>
<p dir="rtl">هنگامی که برنامه رو باز میکنین رو قسمت کاربران پنل اون دستگاه به صورت آنلاین نمایش داده میشه؟ (یک نوار سبز بالای کارت دستگاه نمایش داده میشه)</p>
<p dir="rtl">آیا قسمت <a href="https://doc.chabokpush.com/javascript/troubleshoot.html">عیب یابی</a> را مطالعه نموده اید؟</p>

**Comment by shdehnavi** [comment]
> آیا دستگاه از طریق vpn به اینترنت متصل هست؟
> 
> هنگامی که برنامه رو باز میکنین رو قسمت کاربران پنل اون دستگاه به صورت آنلاین نمایش داده میشه؟ (یک نوار سبز بالای کارت دستگاه نمایش داده میشه)
> 
> آیا قسمت [عیب یابی](https://doc.chabokpush.com/javascript/troubleshoot.html) را مطالعه نموده اید؟

بله همه این موارد رو چککردم، مشکل این بود که مرورگر رو به خاطر جلوگیری از CORS در حالت  disabled-web-security اجرا کرده بودم و پوش ناتیفیکیشن در اون حالت کارنمیکرد



> سلام
> 
> خطای فوق زمانی رخ میدهد که سرویس ورکر نتواند توکن بگیرد
> 
> و از آنجایی که در iOS وب پوش توسط اپل پشتیبانی نمی‌شود امکان دریافت توکن نیست.
> 
> > با اینکه این ارور رو میگیرم ولی توی پنل چابک میبینم که دستگاه ثبت شده
> 
> بله دستگاه ثبت می‌شود ولی توکنی برای ارسال به کاربر وجود نخواهد داشت

این مورد ولی بعضی مواقع رخ میده، وقتی سایت رو از طریق کروم دسکتاپ بازمیکنم مشکلی نیست، ولی توی گوشی اندرویدی وقتی بازمیکنم این ارور رو باز مشاهده می کنم.

**Comment by amir-yaghoobi** [comment]
<blockquote dir="rtl">
<p dir="rtl">این مورد ولی بعضی مواقع رخ میده، وقتی سایت رو از طریق کروم دسکتاپ بازمیکنم مشکلی نیست، ولی توی گوشی اندرویدی وقتی بازمیکنم این ارور رو باز مشاهده می کنم.</p>
</blockquote>
<p dir="rtl">لطفا در صورت امکان مدل گوشی، نسخه سیستم عامل و مرورگر و نسخه مرورگر رو اطلاع بدین تا علت رو ببرسی کنیم</p>

**Comment by Husseinhj** [comment]
این موضوع در نسخه [۱.۲.۳](https://doc.chabokpush.com/javascript/release-note.html#%D9%86%D8%B3%D8%AE%D9%87-%DB%B1%DB%B2%DB%B3---%DB%B1%DB%B3%DB%B9%DB%B8%DB%B0%DB%B1%DB%B2%DB%B1) حل شده است.
