### ISSUE TITLE
مشکل در نمایش وب پوش در اندروید

### ISSUE THREAD

**Issue by romid7** [chabokpush/chabok-client-js#21]
تو پنل کاربری زده میشه تحویل داده شده ولی تو اندروید نمایش داده نمیشه، رو دسکتاپ مشکلی نداره نمایش میده
مشکل از کجا میتونه باشه؟

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">سلام</p>
<p dir="rtl">از چه مرورگری و چه نسخه ای استفاده میکنین؟</p>
<p dir="rtl">زمان ارسال پیام مرورگر باز هست یا بسته؟</p>
<p dir="rtl">از چه نسخه ای از <code>sdk</code> استفاده میکنین و در صورت امکان <code>appId</code> خودتون رو بگین تا بیشتر بررسی کنیم</p>

**Comment by romid7** [comment]
از مرورگر کروم و مرورگر خود سامسونگ استفاده میکنم؟
بله زمان ارسال هم مرورگر باز هستش
نسخه sdk 1.2.1 هستش
appId : pucrarvin
ممنون

**Comment by romid7** [comment]
سلام، دوست عزیز 
مشکل از سمت ما هستش؟

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">در حال بررسی هستیم</p>

<p dir="rtl">بر روی تست‌هایی که ما انجام دادیم مشکل خاصی ندیدیم</p>
<p dir="rtl">در صورت امکان یک بار به وسیله <a href="https://webpush.chabokpush.com/">سمپل وب ما</a> که کد آن در <a href="https://github.com/chabokpush/chabok-client-js/tree/master/sample">این  ریپو</a>  قرار دارد بررسی کنید</p>

**Comment by behrad** [comment]
@amir-yaghoobi

**Comment by Husseinhj** [comment]
<p dir="rtl">این موضوع در نسخه <a href="https://doc.chabokpush.com/javascript/release-note.html#%D9%86%D8%B3%D8%AE%D9%87-%DB%B1%DB%B4%DB%B0---%DB%B1%DB%B3%DB%B9%DB%B8%DB%B0%DB%B4%DB%B1%DB%B8">۱.۴.۰</a> حل شده است.</p>
