### ISSUE TITLE
مشکلات در اتصال

### ISSUE THREAD

**Issue by webtinax** [chabokpush/chabok-client-js#3]
با سلام خدمت شما

1:
نکته امنیتی : مقدار USER_ID را هرگز به صورت خام در LocalStorage ذخیره نکنید، چون این مقدار شناسه معنادار می‌باشد و می‌توان با آن کاربر را روی چابک ثبت‌نام کرد. برای این منظور می‌توانید از متد ()chabok.getUserId چابک استفاده کنید که شناسه کاربر را به صورت رمزنگاری شده نگه‌می‌دارد.

این را دقیقتر توضیح دهید 

2: ما زمانی که
devMode: true
را فالس میذاریم خطا دریافت میکنیم
متن خطا به این صورت هست ::
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
chabokpush.min.js:8 Uncaught (in promise) Error: Network Error
    at t.exports (chabokpush.min.js:8)
    at XMLHttpRequest.d.onerror (chabokpush.min.js:8)
در رابطه با تفاوت خاموش بودن یا روشن بودن این گزینه توضیح بفرمائید که اصلا به چه کاری میاد و چه فرقی میکنه

**Comment by amir-yaghoobi** [comment]
<div dir="rtl">
سلام</br>
<h2>۱</h2>
<p>
به طور ساده بخوام بیان کنم، شما برای کاربرهاتون شناسه دلخواه خودتون رو میذارین مثلا شماره تلفن یا ایمیل یا کد ایجاد شود توسط سیستم خودتون، که با این <code>USER_ID</code> امکان ارسال پوش به کاربر رو دارین. 
در صورتی که در سمت کلاینت(وب) نیاز به ذخیره شناسه در LocalStorage و استفاده از اون رو داشته باشین بهتره خودتون این ذخیره رو انجام ندین، SDK چابک این کار رو با رمزنگاری انجام میده تا شناسه کاربر ثبت شده به راحتی قابل دسترس نباشه و جهت دریافت دوباره این شناسه و استفاده در کد سمت کلاینت از متد<code dir="ltr">chabok.getUserId()</code>استفاده کنید.
</p>
<h2>۲</h2>

چابک شامل ۲ محیط می‌باشد (سندباکس و عملیاتی)
حساب‌های رایگان چابک (تا 30هزار کاربر رایگان) بر روی محیط سندباکس قرار میگیرن.

مقدار <code>true</code> برای ‌<code>devMode</code> باعث اتصال به محیط سندباکس و مقدار <code>false</code> باعث اتصال به محیط عملیاتی ما می‌شود.</br>

از آنجایی که حساب‌کاربری شما بر روی سندباکس قرار دارد امکان اتصال و استفاده از محیط عملیاتی برای شما وجود ندارد به همین خاطر خطا دریافت می‌کنید.
</div>

**Comment by webtinax** [comment]
بسیارعالی ممنون بابت توضیحات
لطفا توضیحی که در رابطه با سوال دوم داده شد را در قسمت راهنمای اتصال که متن اشاره شده قرار داره هم بذارید خیلی ها شاید متوجه نشوند بخاطر اینکه گفتید برای عملیاتی شدن حالت را تغییر بدید من بعنوان برنامه نویس فکر کردم این حالت برای دیباگ کردن هست

ممنون بابت پاسخگویی عالی و سریعتون

**Comment by amir-yaghoobi** [comment]
<div dir="rtl">
<p>ممنون به خاطر پیشنهادتون</p>
متاسفانه مستندات ما هنوز به اون پختگی لازم نرسیده، این موضوع رو منتقل میکنم تا توضیحات اضافه بشن.
</br></br>
من این issue رو میبندم اگه همچنان موردی بود لطفا دوباره باز کنین.
</br>با تشکر
</div>
