### ISSUE TITLE
مشکل نوتیفیکیشن در پس زمینه

### ISSUE THREAD

**Issue by webtinax** [chabokpush/chabok-client-js#4]
سلام وقت بخیر
سیستم را بطور دقیق نصب کردم

فایل
ChabokSDKWorker.js
را در پوشه ی روت سایت قرار دادم

بعد در فایل جاوا اسکریپ صفحه این را قرار دادم
`if('serviceWorker' in navigator && 'PushManager' in window && 'Notification' in window) {
        const authConfig = {
            appId: '-----------',
            apiKey: '----------------------',
            username: '--------------------',
            password: '-----------------------',
            devMode: true
        };
        const options = {
            webpush: {
                enabled: true,
                publicKey: '-------------------------------'
            },
            silent: false
        };
        chabok = new chabokpush.Chabok(authConfig, options);
    }`
و مشخصات کاربری را بطور دقیق تکمیل کردم

بعد از اون کاربر را در چابک ثبت نام کردم توسط کد زیر
chabok.register('---------------------');
بجای خط فاصله ها شناسه ای برای کاربر در نظر گرفتم

سرویس ورکر نصب شد و تمامی مراحل با موفقیت انجام شد و کاربر به درستی در چابک ثبت شد ، اما مشکلی که پیش اومده اینه که وب نوتیفیکیشن ها فقط وقتی میان که تب مرورگر مربوط به سایت باز باشه ، وقتی مرورگر بسته باشه یا روی یه تب دیگه باشه نوتیفیکیشن نمیاد و در پنل کاربری هم پیامی که میاد اینه : 

این پیام هنوز تحویل داده نشده است

این روال ادامه پیدا میکنه تا وقتی من سایت رو باز کنم و یا تب را فعال کنم و یکباره نوتیفیکیش های ارسالی میان در واقع انگار سرویس ورکر کار نمیکنه من اومدم یکسری تست هم انجام دادم قبل از اون بگم ارسال نوتیفیکیشن را به این صورت انجام دادم : 

وارد این آدرس شدم : 
https://api.doc.chabokpush.com/#/push/push_toUsers

کانکشن را با زدن قفل و وارد کردن 
access_token
برقرار کردم و از قسمت 
push_toUsers
با وارد کردن آیدی شخص در قیمت یوزر و تعیین کانال دیفالت ارسال را انجام دادم

`{
  "user": "09635634564",
  "channel": "default",
  "content": "string",
  "data": {},
  "trackId": "string",
  "inApp": false,
  "live": false,
  "useAsAlert": false,
  "alertText": "string",
  "ttl": 0,
  "fallback": {},
  "clientId": "string",
  "notification": {
    "title": "rtertertergdf",
    "body": "gdfgdgdfgdfgdgdgd",
    "sound": "string",
    "actions": [
      {}
    ],
    "mediaType": "string",
    "mediaUrl": "string",
    "contentAvailable": true,
    "mutableContent": true,
    "category": "string"
  },
  "idr": false,
  "silent": true,
  "contentBinary": "string",
  "contentType": "string",
  "id": 0
}`

===================================
مشکل به وجود آمده با پیاده سازی شرایط ذکر شده برای من پیش اومد
من که از سرویس ورکرها تا حدود زیادی سر در میارم وارد فایل سرویس ورکر شدم و در قسمت پوش که مربوط به سرویس ورکر هست یه لاگ هم گذاشتم

`self.addEventListener("push", function (t) {
                console.log('hiiiiii');
                if (t.data.json()) {
                    var n = t.data.json();
                    t.waitUntil(self.registration.showNotification(n.title, n))
                }
            }`

اما سیستم لاگ رو نمیگیره انگار اصلا اونت لیسنر مربوط به پوش صدا زده نمیشه
لطفا در این خصوص راهنمایی نمائید

**Comment by webtinax** [comment]
این مشکل را در پروژه ی دیگه ای هم که داریم و با همین روال پیاده سازی شده مشاهده کردیم

**Comment by behrad** [comment]
وب پوش فقط روی سایت‌هایی که اس اس ال دارند کار می ‌کند.
آیا سایت یا نمونه شما دارای اس اس ال هستش؟

**Comment by webtinax** [comment]
بله اس اس ال فعال هست 
کدها اصلاح شد و با تگ کد نوشتم
نوتیفیکیشن تست این مشکل را نداره

یوزر را ستاره گذاشتم
`{
  "user": "*",
  "channel": "default",
  "content": "string",
  "data": {},
  "trackId": "string",
  "inApp": false,
  "live": false,
  "useAsAlert": false,
  "alertText": "string",
  "ttl": 0,
  "fallback": {},
  "clientId": "string",
  "notification": {
    "title": "string",
    "body": "string",
    "sound": "string",
    "actions": [
      {}
    ],
    "mediaType": "string",
    "mediaUrl": "string",
    "contentAvailable": true,
    "mutableContent": true,
    "category": "string"
  },
  "idr": false,
  "silent": true,
  "contentBinary": "string",
  "contentType": "string",
  "id": 0
}`

بعد وقتی ارسال میزنم این پیام رو میده ویندوز
[http://golpashahr.com/1.PNG](url)

**Comment by behrad** [comment]
> کدها اصلاح شد و با تگ کد نوشتم

برای کد های طولانی از مارک اپ چند خطی استفاده کنید

یوزر رو به آیدی یکی از کاربران تست تغیییر بدید جای ستاره و فقط کلید‌های لازم رو بفرستید
و عین اون چیزی که می فرستید رو لطفن پست کنید اینجا

**Comment by behrad** [comment]
خب طبیعتن وقتی از سایلینت استفاده کنید نوتیفیکیشنی دریافت نمیشه
همچنین اگر اکشن رو ست میکنید باید مقدار مناسبی توش بگذارید

خوشحالمم که مشکلتون حل شد
