### ISSUE TITLE
افزودن دسته جمعی تگ ها

### ISSUE THREAD

**Issue by webtinax** [chabokpush/chabok-client-js#5]
سلام وقت بخیر
با توجه به اینکه شخص در یک وب سایت معمولا 15 تا 20 ثانیه وقت صرف خواهد کرد
نمیشه معمولا تمامی تگ ها را به درستی اضافه کرد برای شخص
ما حدود 100 تگ میخوایم برای هر کاربر تنظیم کنیم و این نیازمند یه امکان هست که بشه دسته جمعی تگ ها را اضافه کرد

لطفا این قابلیت که بشه گروهی برای یک شخص تگ تعریف کرد را به سیستم اضافه کنید ممنون

**Comment by behrad** [comment]
صد تگ برای هر کاربر؟

**Comment by behrad** [comment]
در نسخه آتی پشتیبانی از چند تگ همزمان رو اضافه خواهیم کرد
@amir-yaghoobi

**Comment by amir-yaghoobi** [comment]
<div dir="rtl">
@webtinax 
پشتیبانی از چند تگ همزمان به API های چابک اضافه شد.</br>
‍‍‍‍<pre dir="ltr">POST /installations/addTags </pre>
اطلاعات بیشتر و نحوه استفاده از این API رو میتونین در <a href ="https://api.doc.chabokpush.com/#/installation/installation_addTags"> این بخش از مستندات </a> مشاهده نمایید.
</br>
من این issue رو میبندم اگه سوال دیگه ای در این مورد داشتن دوباره باز کنینش.
</div>

**Comment by webtinax** [comment]
وقت بخیر
متاسفانه این ای پی ای در جاوا اسکریپت افزوده نشده هنوز
chabok.addTags
