### ISSUE TITLE
افزودن ionic

### ISSUE THREAD

**Issue by SajjadKharrazi** [chabokpush/chabok-client-js#6]
سلام
برنامه ای برای اضافه کردن و پشتیبانی از آیونیک ندارید؟
خیلی مهم و نیازه برای استارتاپ ها

**Comment by behrad** [comment]
ما هنوز برنامه‌ای براش نداریم اما
نوشتن یک افزونه روی همین کتابخانه جاوا اسکریپت برای آیونیک فکر نمیکنم کار خیلی پیچیده ای باشه

شما اپلیکیشنی دارید  که با آیونیک باشه؟

**Comment by SajjadKharrazi** [comment]
بله خودم ۲تا
دوستان هم میدونم ک دارن
وان سیگنال که تحریم کرد همه میچرخیم دور هم :(

**Comment by behrad** [comment]
اگر وقت کافی داشته باشید خوشحال میشیم با کمک شما یک رپر دور همین کتابخانه درست کنیم

**Comment by SajjadKharrazi** [comment]
واقعیتش اونقدی تخصصش رو ندارم
امیدمون به شما بود

**Comment by behrad** [comment]
سمت ما موضوع زمان و بک لاگ‌های فعلی مون هست
اگر براتون خیلی فورس هست و تعداد کاربراتون فراتر از اکانت رایگان چابک با ما مکاتبه کنید
