### ISSUE TITLE
custom notification

### ISSUE THREAD

**Issue by shahrzadNazemi** [chabokpush/chabok-client-js#7]
سلام.میشه یه مثال یا حداقل توضیحی راجع به آرگومانهایی که نوتیفیکیشن میگیره تا بتونیم کاستومش کنیم بدین ؟و اینکه کجا میتونیم لینکی که نوتیفیکیشن روش کلیک میخوره میره رو ست کنیم ؟

**Comment by amir-yaghoobi** [comment]
<div dir="rtl">سلام </br></br>
<blockquote>میشه یه مثال یا حداقل توضیحی راجع به آرگومانهایی که نوتیفیکیشن میگیره تا بتونیم کاستومش کنیم بدین ؟</blockquote>
در حال حاضر نوتیفیکشن‌های دریافتی وب رو میتونین با کلید‌های <code>title</code> ، <code>body</code> و <code>icon</code> .شخصی سازی کنین

<pre dir="ltr">
...

notification: {
   title: "sample",
   body: "this is a test",
   icon: "http://link-to-icon.com/image.png"
}

...
</pre>

<blockquote> لینکی که نوتیفیکیشن روش کلیک میخوره میره رو ست کنیم ؟</blockquote>
در نسخه فعلی sdk این امکان وجود ندارد اما در نسخه بعدی که در هفته بعد منتشر میشه این امکان نیز اضافه میگردد.
</div>

**Comment by shahrzadNazemi** [comment]
:ممنون.آخه برای نوتیفیکیشن یه سری آرگومان دیگه هم هست که نفهمیدم اونا برای چی هست.مثل

- "actions": [
      {}
    ],
    "mediaType": "string",
    "mediaUrl": "string",
    "contentAvailable": true,
    "mutableContent": true,
    "category": "string"
و اینکه این امکان لینک نوتیفیکیشن دقیقا کی آماده میشه ؟من لازمش دارم

**Comment by amir-yaghoobi** [comment]
<div dir="rtl">
<blockquote>ممنون.آخه برای نوتیفیکیشن یه سری آرگومان دیگه هم هست که نفهمیدم اونا برای چی هست.</blockquote>

موارد فوق به منظور ارسال <b>Rich push notification</b> در اندروید و ios می‌باشند و در sdk وب ما در حال حاضر فعال نیستند. 

<blockquote>و اینکه این امکان لینک نوتیفیکیشن دقیقا کی آماده میشه ؟</blockquote>
نسخه بعدی sdk وب ما هفته بعدی منتشر میشه و این امکان نیز در این نسخه اضافه شده.
</div>

**Comment by shahrzadNazemi** [comment]
مرسی
