### ISSUE TITLE
مشکل افزودن تگ

### ISSUE THREAD

**Issue by webtinax** [chabokpush/chabok-client-js#8]
مشکل در افزودن تگ به کاربر توسط جاوا اسکریپت

![sadasd](https://user-images.githubusercontent.com/14169430/44882586-36a53200-acc9-11e8-8f2a-01441ea947bf.PNG)

**Comment by behrad** [comment]
We will release next JS SDK version this following week, As mentioned in #5

**Comment by webtinax** [comment]
chabok.addtags
این رو هم اضافه کنید بی زحمت که بشه از طریق جاوا اسکریپت هم تگ ها را دسته جمعی اضافه کرد

**Comment by behrad** [comment]
در همین نسخه اضافه خواهد شد

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">متد درخواستی در نسخه <a href="https://www.npmjs.com/package/chabokpush">v1.0.1</a> اضافه شد</p>
<pre><code class="language-javascript">
chabok.addTag(&#39;TAG&#39;)
chabok.addTags(&#39;TAG1&#39;, &#39;TAG2&#39;, &#39;TAG3&#39;)
</code></pre>
<p dir="rtl">در صورتی که همچنان در این مورد مشکلی داشتید دوباره این issue رو باز کنین</p>

**Comment by webtinax** [comment]
chabok.removeTags('TAG1', 'TAG2', 'TAG3')

این مورد را هم به همه ی قسمت ها اضافه کنید ممنون 
بخاطر اینکه ممکنه لیست تگ ها اپدیت بشه و شخص گزینه ها را تغییر بده اول باید تمام تگ ها را حذف کنیم بعد تگ های جدید را اضافه کنیم

**Comment by webtinax** [comment]
آقا دمتون گرم این مورد اضافه شده قبلا

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">@webtinax امکان آپدیت تگ‌ها وجود داره</p>
<p dir="rtl">شما با استفاده از متد <code>chabok.removeTags</code> می‌توانید تگ‌هایی که دیگر نیاز نیست را حذف کنید</p>
<pre><code class="language-javascript">chabok.removeTags(&#39;TAG01&#39;, &#39;TAG02&#39;, &#39;TAG03&#39;)
chabok.removeTag(&#39;TAG04&#39;)</code></pre>

**Comment by webtinax** [comment]
نه منظورم اینه کل تگ های ثبت شده را بدون اشاره به نام تگ حذف کنیم

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">این امکان هم در نسخه بعدی sdk ما اضافه خواهد شد.</p>

**Comment by webtinax** [comment]
ببخشید یه مشکل دارم
addTags()
به این تابع باید هر تگ را بعنوان پارامتر ست کنیم درسته ؟
مشکل اینه من تگ هایی که قرار هست اضافه کنم داخل ارایه هست
`var tags_add = ['tag_1','tag_2','tag_3',...........];`

خب راه حلی پیدا نکردم بتونم اعضای یک آرایه را بعنوان پارامترهای تابع قرار بدم در این خصوص راهنمایی بفرمائید
ممنون

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">با استفاده از  <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#A_better_apply">spread</a> در <strong>ES6</strong>:</p>

```javascript
var tags_add = ['tag_1','tag_2','tag_3',...........]
this.chabok.addTags(...tags_add)
```

<p dir="rtl">با استفاده از <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply">apply</a>:</p>

```javascript
var tags_add = ['tag_1','tag_2','tag_3',...........]
this.chabok.addTags.apply(this, tags_add)
```

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">این مورد رو من برای نمونه مطرح کردم و قاعدتا به خاطر رفتار  <code>this</code> در جاواسکریپت متفاوت خواهد بود</p>
<p dir="rtl">پارامتر اول در apply بهتر است <code>this</code>ای باشد که چابک بر روی آن قرار گرفته است. از آنجایی که این مورد کاملا بستگی به نحوه پیاده‌سازی و کد شما دارد راهنمایی بیشتر توسط من امکان پذیر نیست</p>

<blockquote dir="rtl">
<p dir="rtl">نکته: استفاده از <strong>spread</strong> موجود در <strong>ES6</strong> به دلیل عدم نیاز به مدیریت <code>this</code> بهتر می‌باشد</p>
</blockquote>

**Comment by webtinax** [comment]
مشکل با استفاده به این صورت برطرف شد
`var tags_add = ['tag_1','tag_2','tag_3',...........]
chabok.addTags.apply(chabok, tags_add);`
