### ISSUE TITLE
مشکل در اتصال

### ISSUE THREAD

**Issue by Mr-Hqq** [chabokpush/chabok-client-js#9]
<div dir="rtl">سلام و خسته نباشید</div>
<div dir="rtl">من کد های نمونه رو استفاده کردم و هیچ اتفاقی رو پنل چابک نمی افته و روی کنسول خودم ارور زیر رو دریافت می کنم</div>

`POST https://sandbox.push.adpdigital.com/api/installations 500 (Internal Server Error)`

<div dir="rtl">اگه میشه راهنمایی کنید. ممنون</div>

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">سلام، لطفا لاگ‌تریس خطا رو در صورت موجود بودن نیز ارسال کنین.</p>

**Comment by Mr-Hqq** [comment]
<div dir="rtl">فقط لاگ بروزر در دسترسه که اونم دو ارور داره یکی که بالا ارسال کردم یکی دیگه هم از فایله
</div>

> chabokpush.js:8 Uncaught (in promise) Error: Request failed with status code 500
>     at t.exports (chabokpush.js:8)
>     at t.exports (chabokpush.js:14)
>     at XMLHttpRequest.d.(anonymous function) (https://bimocenter.com/chabokpush.js:8:22683)

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">تنظیمات چابک رو به درستی انجام دادین؟ (اطلاعات حساب کاربری)</p>
<p dir="rtl">و این که از چه ورژنی از sdk ما استفاده می‌کنید.</p>

**Comment by Mr-Hqq** [comment]
<div dir="rtl">بله تنظیمات به درستی انجام شده</div>
<div dir="rtl">تو اسکریپت زده `chabokpush - 1.0.0` </div>

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">شما دارین از این <a href="https://github.com/chabokpush/chabok-client-js#sample-usage">نمونه کد</a> استفاده میکنین؟</p>
<p dir="rtl">اگه نه نمونه کد مورد استفاده رو مطرح کنین تا بیشتر بررسی کنیم.</p>

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">این مورد به نحوه پیاده‌سازی، فریم‌ورک مورد استفاده و کد شما بستگی داره</p>
<p dir="rtl">به نظرم با پیاده‌سازی یک <strong dir="rtl">singleton pattern</strong> ساده مشکل شما حل بشه</p>

**Comment by amir-yaghoobi** [comment]
<p dir="rtl">در صورتی که مشکل در مورد نحوه استفاده از چابک رفع نشد دوباره این issue رو باز کنین</p>
